---
- name: Creating auth user...
  user:
    name: "{{ auth_default_user }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ auth_default_user }}@{{ inventory_hostname }}"

- name: Copying public key ...
  shell: "cat /home/{{ auth_default_user }}/.ssh/id_rsa.pub"
  register: pub_key

- set_fact: support_key="{{ pub_key['stdout'] }}"
