group: deprecated-2017Q2

sudo: required

language: bash

services:
  - docker

before_install:
  - env
  - docker pull koalaman/shellcheck
  - docker pull eeacms/pyflakes

script:
  - docker run -v "$(pwd):/mnt:ro" koalaman/shellcheck -s bash -e SC1091,SC1090 shared/bash.sh shared/bootstrap.sh scripts/fix-perms.sh
  - docker run -v "$(pwd):/code:ro" eeacms/pyflakes
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - pip install ansible
  - cd ansible; ansible-playbook main.yml --tags auth-deploy

matrix:
  fast_finish: true

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify