group: deprecated-2017Q2

sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck
  - docker pull eeacms/pyflakes

script:
 - docker run -v "$(pwd):/mnt:ro" koalaman/shellcheck -s bash -e SC1091,SC1090 shared/bash.sh shared/bootstrap.sh scripts/fix-perms.sh
 - docker run -v "$(pwd):/code:ro" eeacms/pyflakes

matrix:
  fast_finish: true