group: deprecated-2017Q2

sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/mnt koalaman/shellcheck -s bash -e SC1091,SC1090 shared/bash.sh shared/bootstrap.sh scripts/fix-perms.sh
 - docker run -v $(pwd):/code eeacms/pyflakes

matrix:
  fast_finish: true